[package]
name = "pang-streaming-server"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
scuffle-rtmp = "0.2.3"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.225", features = ["derive"] }
toml = "0.9.6"
reqwest = { version = "0.12.23", features = ["json"] }
