services:
  pang-streaming-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pang-streaming-server
    restart: unless-stopped
    ports:
      - "1936:1935"  # 내부 1935, 외부 1936으로 변경
      - "8081:8081"
    volumes:
      - ./hls_output:/app/hls_output
      - ./deploy/configs/config.toml:/app/config.toml:ro
    networks:
      - pang-network

  srs:
    image: ossrs/srs:5
    container_name: srs-server
    restart: unless-stopped
    volumes:
      - ./deploy/configs/srs.conf:/usr/local/srs/conf/srs.conf:ro
      - ./hls_output:/usr/local/srs/objs/nginx/html  # HLS 파일 공유
    command: ["./objs/srs", "-c", "conf/srs.conf"]
    depends_on:
      - pang-streaming-server
    ports:
      - "1985:1985"    # HTTP API
      - "8080:8080"    # HTTP (HLS, WHIP, WHEP)
      - "8000:8000/udp" # WebRTC
    networks:
      - pang-network

networks:
  pang-network:
    driver: bridge

volumes:
  hls_output:
    driver: local